r_with_python
jtr13/cc21fall2 pull request #107
Opened 2021-11-05 19:00 UTC by WayneFd

submission of r_with_python file

2021-11-07 01:46 UTC, alexnsaunders requested changes

2021-11-07 01:46 UTC, alexnsaunders commented on r_with_python.Rmd
> +## 1.Introduction
No numbers after hashtags please

2021-11-07 01:46 UTC, alexnsaunders commented on r_with_python.Rmd
> +### 2.1 Installation
number after hashtag - many examples in your files..

2021-11-07 02:17 UTC, alexnsaunders commented
thanks 🎉

2021-11-07 02:17 UTC, merged

2021-11-08 10:48 UTC, jtr13 commented
The build fails for this chapter since we don't have Python set up to run. I set eval=FALSE to get around this issue. We may be able to fix it, will discuss with collaborators.

2021-11-17 05:01 UTC, alexnsaunders commented
https://jtr13.github.io/cc21fall2/integrate-r-with-python.html Here is your chapter congrats!