Add files via upload
jtr13/cc21fall2 pull request #119
Opened 2021-11-05 22:34 UTC by zezhong5

Add tutorial of making and analyzing graph by base r and ggplot2

2021-11-06 21:45 UTC, nicric99 commented on ggplot_base_r_graph_analysis.Rmd
> +---
The whole YAML introduction should be cancelled including the --- lines . Instead, fix it with an introduction like this:
#Title of your project
**white line**
Your name
**white line ** 

Put the hashtag in front of the title of your project as it is marked above.

2021-11-06 21:47 UTC, nicric99 commented on ggplot_base_r_graph_analysis.Rmd
> +---
The whole YAML introduction (the part with title: author: etc...) should be cancelled including the --- lines . Instead, fix it with an introduction like this:
#Title of your project
_white line_
Your name
_white line _

Put the hashtag in front of the title of your project as it is marked above.

2021-11-06 21:49 UTC, nicric99 commented on ggplot_base_r_graph_analysis.Rmd
> +***Bar Chart***
Suggestion: to create subheadings you can change the '***' to '##'
Remember  just two hashtags, (don't mark subheading with a single #)

2021-11-06 21:54 UTC, nicric99 requested changes
The whole YAML introduction (the part with title: author: ... from line 1 to line 6) should be cancelled including the --- lines . Instead, fix it with an introduction like this:
#Title of your project
white line
Your name
_white line _

Put the hashtag in front of the title of your project as it is marked above.


Suggestion: to create subheadings you can change the '***' to '##'
Remember just two hashtags, (don't mark subheading with a single #). For instance the occurrence on lines 13, 27, etc..

2021-11-15 03:27 UTC, jtr13 commented
@nicric99 It looks like all the changes that were requested were made a week ago. Can you please review and merge if everything looks ok? Thanks.

2021-11-15 03:38 UTC, nicric99 requested changes
Other hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings. Correct: ## Subheading. Incorrect: ## 3. Subheading.

2021-11-17 00:43 UTC, merged

2021-11-17 00:44 UTC, nicric99 commented
Congrats 🎉