Scrape Twitter with R
jtr13/cc21fall2 pull request #15
Opened 2021-11-02 19:06 UTC by JasonSqz

Submission for Senqi Zhang. Reach out to me if there is any issue!

2021-11-03 23:58 UTC, Francis-ZY-Yuan commented on Scrape_Twitter_R.Rmd
> +## 1.Preparation
Please remove the numbering in subheadings. They'll be automatically generated when rendering.

2021-11-03 23:58 UTC, Francis-ZY-Yuan commented on Scrape_Twitter_R.Rmd
> +![](resources/Scrape_Twitter_R/f1.png)
Seems this file is not in your commit.

2021-11-04 00:08 UTC, Francis-ZY-Yuan commented on Scrape_Twitter_R.Rmd
> +write_as_csv(covid_df2, "covid_df", na ="NA")
Avoid writing files. Might create problems when rendering.

2021-11-04 00:11 UTC, Francis-ZY-Yuan commented
The Rmd filename should be lowercase.

2021-11-04 00:15 UTC, Francis-ZY-Yuan requested changes
There are some minor modifications needed before we merge it into main (see the comments).

2021-11-05 01:00 UTC, JasonSqz commented
I made the modifications as requested and pushed again. Is that all I need to do?

2021-11-05 21:35 UTC, Francis-ZY-Yuan commented on Scrape_Twitter_R.Rmd
> +## 1.Preparation
These numberings also need to be removed.

2021-11-05 21:36 UTC, Francis-ZY-Yuan commented
Numberings like 1. should also be removed.

2021-11-05 23:53 UTC, JasonSqz commented
fixed

2021-11-07 03:18 UTC, merged

2021-11-07 03:18 UTC, Francis-ZY-Yuan commented
Merged into main. Thanks!

2021-11-08 02:27 UTC, jtr13 commented
This chapter as written doesn't render since the code needs to work beyond the initial run. For now eval is set to FALSE in the code chunks but we can solve this by adding the tokens to GitHub secrets and then access them with GitHub actions. We did that for another chapter: https://jtr13.github.io/cc21fall2/video-introduction-to-maps-with-ggmap.html @JasonSqz : it's up to you if you want to go this route or leave as is

2021-11-10 16:01 UTC, JasonSqz commented
I'd love to add the tokens to GitHub secrets. Though, I am not sure what I need to do.

2021-11-10 16:08 UTC, jtr13 commented
@rjr2168 can you help @JasonSqz with this?

2021-11-10 19:59 UTC, rjr2168 commented
Sure thing! @JasonSqz I'll refer you to my post on the subject: https://edstem.org/us/courses/12766/discussion/829392 . Let me know how I can help! I've been made a contributor on this project, so I can help you modify the bookdown.yaml file if you need assistance.

2021-11-11 00:09 UTC, JasonSqz commented
@rjr2168 Hi, I read through the post and I am wondering if the secret is already added. I think I do not have the permission to do this.

2021-11-11 02:57 UTC, rjr2168 commented
That is correct, @JasonSqz, only the professor can add secrets to the project. You will have to ask her to add one on your behalf.