Adding Predictive Analytics RMD file
jtr13/cc21fall2 pull request #22
Opened 2021-11-03 14:43 UTC by rjrahul24

Attached is the .Rmd file for my community contribution.

There is one external package that needs direct installation from GitHub. Details are mentioned in comments. 
require(devtools) 
install_github("jbryer/makeR")

2021-11-05 00:17 UTC, rjrahul24 commented
@pyropig @Abhimanyu210100 Are any changes required? Unsure why the PR was assigned back to me?

2021-11-05 00:22 UTC, pyropig commented
> @pyropig @Abhimanyu210100 Are any changes required? Unsure why the PR was assigned back to me?

I'm not the assigner but I guess it's just a miss-click

2021-11-05 00:33 UTC, pyropig commented
@Abhimanyu210100 could you please assign to another merger? its seems the branch owner is also in the list of assignees so we might need to take care of that

2021-11-05 01:24 UTC, Abhimanyu210100 commented
Hi @rjrahul24 apologies for the assignment, it was by mistake

2021-11-06 19:13 UTC, kq2153 commented on predictive-analytics-r.Rmd
> +```{r setup, include=FALSE}
Please change this to "{r, include=FALSE}"

2021-11-06 19:15 UTC, kq2153 requested changes
Hi, please make the change requested in the comments. Thanks!

2021-11-06 19:18 UTC, rjrahul24 reviewed
@kq2153 Changes reflect in the latest commit. Thanks!

2021-11-16 15:14 UTC, rjrahul24 commented
Hey @kq2153, just checking back to see if there are any more changes needed from my end?

2021-11-18 00:03 UTC, kq2153 approved these changes

2021-11-18 00:03 UTC, merged

2021-11-18 23:15 UTC, alexnsaunders commented on predictive-analytics-r.Rmd
> +```{r Package Imports, echo=FALSE, include=TRUE}
> @jtr13 just wanted to double check, but will having "include = TRUE" on these packages cause any issues in the bookdown?

Yes this is causing an issue looks like it needs to be installed directly in github which is beyond the limits of my knowledge - we can do or we will have to take out - package makeR not on CRAN anymore @jtr13

2021-11-19 00:35 UTC, jtr13 commented
I've only seen `include = FALSE` in use but `include=TRUE` won't affect anything -- it just controls whether the code and output are displayed in the rendered version. 

If a package is not available on CRAN but is on GitHub, the remote needs to be specified at the end of the `DESCRIPTION` file. Note that the package name appears in two places: both in the Imports section and in the remotes section.

2021-11-19 04:41 UTC, kq2153 commented
I added the github remote reference to the end of the Description file, uncommented this Rmd file and it seems the bookdown compiled!

2021-11-19 04:54 UTC, jtr13 commented
Woohoo, nice work! 🎉  You can close any issues related to the problem that you fixed.