Neo4j python implementation
jtr13/cc21fall2 pull request #96
Opened 2021-11-05 17:30 UTC by yc4007

Neo4j python implementation for graph generation

2021-11-06 16:39 UTC, kq2153 commented on CommunityContribution.Rmd
> +---
Please delete this line (the file should not have "---" in it

2021-11-06 16:41 UTC, kq2153 commented on CommunityContribution.Rmd
> +title: "Community Contribution"
The first line of the document should start with a single "#" followed by a single whitespace, followed by your project title. 
e.x) # Neo4j python implementation

2021-11-06 16:42 UTC, kq2153 commented on CommunityContribution.Rmd
> +author: Yuxin Cui
The line after the title should be blank
The 3rd line is your name (without the "author:")

2021-11-06 16:43 UTC, kq2153 commented on CommunityContribution.Rmd
> +```{r setup, include=FALSE}
please delete the "setup": 
this should be ```{r, include = FALSE}```

2021-11-06 16:43 UTC, kq2153 commented on CommunityContribution.Rmd
> +html_document: default
You don't need this

2021-11-06 16:44 UTC, kq2153 requested changes
Please make changes to address the comments made. Thanks!

2021-11-17 18:29 UTC, kq2153 commented
@yc4007 Hi, would you please be able to make the changes requested? This cannot be merged until those changes are made. Thanks!

2021-11-19 03:11 UTC, kq2153 commented
@yc4007 Hi, just checking in but would you be able to make the edits suggested above? Once these format changes are made, the file can be safely merged into the rest of the CC bookdown. Thanks!

2021-11-19 16:46 UTC, yc4007 commented
Sure I will change them right now.

On Thu, Nov 18, 2021 at 10:12 PM kq2153 ***@***.***> wrote:

> @yc4007 <https://github.com/yc4007> Hi, just checking in but would you be
> able to make the edits suggested above? Once these format changes are made,
> the file can be safely merged into the rest of the CC bookdown. Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jtr13/cc21fall2/pull/96#issuecomment-973691647>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWGYWFQGAWIL4T4ADUSEOS3UMW6ATANCNFSM5HOK3GAA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-19 17:06 UTC, yc4007 commented
Hi,

Thank you for the reminding email. I have forced pull my newest changes to
branch py2neo. Could you help me delete my old branch neo4j?

Thank you!

On Thu, Nov 18, 2021 at 10:12 PM kq2153 ***@***.***> wrote:

> @yc4007 <https://github.com/yc4007> Hi, just checking in but would you be
> able to make the edits suggested above? Once these format changes are made,
> the file can be safely merged into the rest of the CC bookdown. Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jtr13/cc21fall2/pull/96#issuecomment-973691647>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWGYWFQGAWIL4T4ADUSEOS3UMW6ATANCNFSM5HOK3GAA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-23 21:19 UTC, kq2153 commented
Hi, sorry just saw this. It shows that the pull request is coming from py2neo now so I think it's fine unless there is another pull request coming from your old branch as well. 

Also @yc4007 would you be able to rename your .Rmd file? The requirements for the filename are:

-  words only and joined with underscores, no white space
- all lowercase letters (e.g neo_python_implementation.Rmd)

Also for the author name, it only needs to be your name; you can remove the "author:" 

Thanks!

2021-11-29 21:03 UTC, kq2153 commented
@yc4007 Hi, would you be able to make the 2 last changes (renaming the RMD file and fixing the author line")? Thank you!

2021-12-11 22:20 UTC, yc4007 commented
Geez yes sorry for the late response. I force pushed again. Let me know if
you are able to see it.
My apologies,
Yuxin

On Mon, Nov 29, 2021 at 4:03 PM kq2153 ***@***.***> wrote:

> @yc4007 <https://github.com/yc4007> Hi, would you be able to make the 2
> last changes (renaming the RMD file and fixing the author line")? Thank you!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jtr13/cc21fall2/pull/96#issuecomment-982020714>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWGYWFXF2QX6YQSN3X37U63UOPTC3ANCNFSM5HOK3GAA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-12-19 18:25 UTC, merged